sudo: required

language: python
python:
  - "3.8"

services:
  - docker

before_script:
  - docker-compose build

script:
  - docker-compose run --rm web bash -c "python wait_for_postgres.py &&
                                         pytest --cov-report=xml --cov=./ tests/"

# push results to CodeCov
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Don't email me the results of the test runs
notifications:
  email: false

cache:
  pip: true
