site_name: yadrta
site_description: Yet Another Djando REST Todo App (YADRTA) using django rest and django with OpenAPI Specification.
repo_url: https://github.com/serhatteker/yadrta
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/serhatteker">serhatteker</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
