version: '3'

services:
  postgres:
    image: postgres:11.6

  django:
    restart: always
    env_file:
      - ./.envs/.stage/.django
    build:
      context: .
      dockerfile: ./compose/stage/django/Dockerfile
    image: django_stage_yadrta
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    command: >
      bash -c "python wait_for_postgres.py &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
